services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
    deploy:
      update_config:
        order: start-first
  db-update:
    image: ${REGISTRY}/reactlith-template/db-update:latest
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:mysecretpassword@db:5432/postgres}
    networks:
      - db-network
    deploy:
      mode: replicated-job
  web:
    image: ${REGISTRY}/reactlith-template/web:latest
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:mysecretpassword@db:5432/postgres}
    networks:
      - db-network
    deploy:
      update_config:
        order: start-first

networks:
  db-network:

volumes:
  db-data:
