packages:
  - "apps/*"
  - "tools/*"
  - "packages/*"

catalog:
  "typescript": "5.8.2"
  "@types/bun": "^1.2.13"
  "better-auth": "^1.2.8"
  "superjson": "^2.2.2"
  "zod": "^3.25.24"
  "@t3-oss/env-core": "^0.12.0"
  "hono": "^4.7.10"

catalogs:
  react:
    "react": "~19.0.0"
    "react-dom": "~19.0.0"
    "@types/react": "~19.0.0"
    "@types/react-dom": "~19.0.0"
  trpc:
    "@trpc/server": "^11.1.2"
    "@trpc/client": "^11.1.2"
    "@trpc/tanstack-react-query": "^11.1.2"
    "@tanstack/react-query": "^5.76.1"
  tailwind:
    "tailwindcss": "^4.1.7"
    "@tailwindcss/postcss": "^4.1.7"
    "@tailwindcss/vite": "^4.1.7"
    "postcss": "^8.5.3"
    "tw-animate-css": "^1.3.0"
    "class-variance-authority": "^0.7.1"
    "clsx": "^2.1.1"
    "tailwind-merge": "^3.3.0"
  drizzle:
    "drizzle-orm": "beta"
    "drizzle-kit": "beta"
  vite:
    "vite": "^6.3.5"
    "vite-tsconfig-paths": "^5.1.4"
    "@vitejs/plugin-react": "^4.4.1"
    "@julr/vite-plugin-validate-env": "^1.3.0"
    "@tanstack/router-plugin": "^1.120.5"
    "@tanstack/react-router": "^1.120.5"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

publicHoistPattern:
  - '*prettier*'
  - 'eslint'
