packages:
  - "apps/*"
  - "tools/*"
  - "packages/*"

catalog:
  "typescript": "5.8.2"
  "@types/bun": "^1.2.16"
  "better-auth": "^1.2.9"
  "superjson": "^2.2.2"
  "zod": "^3.25.67"
  "@t3-oss/env-core": "^0.13.8"
  "hono": "^4.8.0"
  "zustand": "^5.0.5"
  "lucide-react": "^0.518.0"

catalogs:
  react:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^19.1.8"
    "@types/react-dom": "^19.1.6"
  trpc:
    "@trpc/server": "^11.4.2"
    "@trpc/client": "^11.4.2"
    "@trpc/tanstack-react-query": "^11.4.2"
    "@tanstack/react-query": "^5.80.10"
  tailwind:
    "tailwindcss": "^4.1.10"
    "@tailwindcss/vite": "^4.1.10"
    "tw-animate-css": "^1.3.4"
    "class-variance-authority": "^0.7.1"
    "clsx": "^2.1.1"
    "tailwind-merge": "^3.3.1"
  drizzle:
    "drizzle-orm": "beta"
    "drizzle-kit": "beta"
  vite:
    "vite": "^6.3.5"
    "vite-tsconfig-paths": "^5.1.4"
    "@vitejs/plugin-react": "^4.5.2"
    "@julr/vite-plugin-validate-env": "^2.1.0"
    "@tanstack/router-plugin": "^1.121.25"
    "@tanstack/react-router": "^1.121.24"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "*prettier*"
  - "eslint"
