/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutNumbersRouteImport } from './routes/_layout/numbers'
import { Route as apiTrpcSplatRouteImport } from './routes/(api)/trpc.$'
import { Route as apiAuthSplatRouteImport } from './routes/(api)/auth.$'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutNumbersRoute = LayoutNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const apiTrpcSplatRoute = apiTrpcSplatRouteImport.update({
  id: '/(api)/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const apiAuthSplatRoute = apiAuthSplatRouteImport.update({
  id: '/(api)/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/numbers': typeof LayoutNumbersRoute
  '/auth/$': typeof apiAuthSplatRoute
  '/trpc/$': typeof apiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/numbers': typeof LayoutNumbersRoute
  '/': typeof LayoutIndexRoute
  '/auth/$': typeof apiAuthSplatRoute
  '/trpc/$': typeof apiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/numbers': typeof LayoutNumbersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/(api)/auth/$': typeof apiAuthSplatRoute
  '/(api)/trpc/$': typeof apiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/numbers' | '/auth/$' | '/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/numbers' | '/' | '/auth/$' | '/trpc/$'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/numbers'
    | '/_layout/'
    | '/(api)/auth/$'
    | '/(api)/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  apiAuthSplatRoute: typeof apiAuthSplatRoute
  apiTrpcSplatRoute: typeof apiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/numbers': {
      id: '/_layout/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof LayoutNumbersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/(api)/trpc/$': {
      id: '/(api)/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof apiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/auth/$': {
      id: '/(api)/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof apiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutNumbersRoute: typeof LayoutNumbersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutNumbersRoute: LayoutNumbersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  apiAuthSplatRoute: apiAuthSplatRoute,
  apiTrpcSplatRoute: apiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
