/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootLayoutRouteRouteImport } from './routes/_rootLayout/route'
import { Route as RootLayoutChar123LocaleChar125RouteRouteImport } from './routes/_rootLayout/{-$locale}/route'
import { Route as RootLayoutChar123LocaleChar125IndexRouteImport } from './routes/_rootLayout/{-$locale}/index'

const RootLayoutRouteRoute = RootLayoutRouteRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutChar123LocaleChar125RouteRoute =
  RootLayoutChar123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)
const RootLayoutChar123LocaleChar125IndexRoute =
  RootLayoutChar123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RootLayoutChar123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof RootLayoutChar123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof RootLayoutChar123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof RootLayoutChar123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_rootLayout': typeof RootLayoutRouteRouteWithChildren
  '/_rootLayout/{-$locale}': typeof RootLayoutChar123LocaleChar125RouteRouteWithChildren
  '/_rootLayout/{-$locale}/': typeof RootLayoutChar123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$locale}' | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$locale}'
  id:
    | '__root__'
    | '/_rootLayout'
    | '/_rootLayout/{-$locale}'
    | '/_rootLayout/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RootLayoutRouteRoute: typeof RootLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/{-$locale}': {
      id: '/_rootLayout/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof RootLayoutChar123LocaleChar125RouteRouteImport
      parentRoute: typeof RootLayoutRouteRoute
    }
    '/_rootLayout/{-$locale}/': {
      id: '/_rootLayout/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof RootLayoutChar123LocaleChar125IndexRouteImport
      parentRoute: typeof RootLayoutChar123LocaleChar125RouteRoute
    }
  }
}

interface RootLayoutChar123LocaleChar125RouteRouteChildren {
  RootLayoutChar123LocaleChar125IndexRoute: typeof RootLayoutChar123LocaleChar125IndexRoute
}

const RootLayoutChar123LocaleChar125RouteRouteChildren: RootLayoutChar123LocaleChar125RouteRouteChildren =
  {
    RootLayoutChar123LocaleChar125IndexRoute:
      RootLayoutChar123LocaleChar125IndexRoute,
  }

const RootLayoutChar123LocaleChar125RouteRouteWithChildren =
  RootLayoutChar123LocaleChar125RouteRoute._addFileChildren(
    RootLayoutChar123LocaleChar125RouteRouteChildren,
  )

interface RootLayoutRouteRouteChildren {
  RootLayoutChar123LocaleChar125RouteRoute: typeof RootLayoutChar123LocaleChar125RouteRouteWithChildren
}

const RootLayoutRouteRouteChildren: RootLayoutRouteRouteChildren = {
  RootLayoutChar123LocaleChar125RouteRoute:
    RootLayoutChar123LocaleChar125RouteRouteWithChildren,
}

const RootLayoutRouteRouteWithChildren = RootLayoutRouteRoute._addFileChildren(
  RootLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RootLayoutRouteRoute: RootLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
